apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-multi-env
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-multi-env
            port:
              number: 80
