apiVersion: v1
kind: Service
metadata:
  name: nginx-broken
  labels:
    app: nginx-broken
spec:
  type: ClusterIP
  selector:
    app: nginx-broken
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
